### ISSUE TITLE
Data load Step 1

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-import#11]
![dataloader_01](https://cloud.githubusercontent.com/assets/791678/9488269/5d6dff9e-4be1-11e5-9030-b68a0259e2ba.jpg)

**Comment by pwalsh** [comment]
## Tasks
- [x] Form for adding files
  - Note the input options:
    - [x] Always an empty input, which is actual two inputs - so the user can upload or paste link
    - [x] Note state change when file is URL
    - [x] Note state change when file is upload (change file)
  - [x] As soon as file field is populated, we run a background check on file via GoodTables API
    - [x] Simple indicator of success/fail onside the form field
    - [x] If fail, div appended to field that prompts user to see the issues
      - [x] on click, opens a modal, showing GoodTables report for this file (same as DataPackagist)
  - [x] Note the button that indicates files are being checked
    - [x] Default state "Waiting for files"  
    - [x] files added but not checked state "Checking files"
    - [x] files added & checked state, where all files are valid "Next" (ie: proceed to step 2)  
    - [x] files added & checked state, where one or more are invalid "Fixes Required" (ie: user needs to go off and fix her source files, and cannot proceed to step 2)
- [x] All this data is mapped into a datapackage (eg: files are resources, name is the title field)
  - [x] We will have a OSDP schema in our registry ([see here](https://github.com/dataprotocols/schemas/pull/12)), but until that is ready, can can use the Tabular Data Package schema
- [x] JSON Table Schema Infer - exactly like when we add resources in DataPackagist, here too we infer a schema when a file is added, and add the schema to the object in the `datapackage.json`
- [x] Test coverage, prefer functional via Zombie, but also any unit tests if required, if we write logic that is not in our dependencies

**Comment by gvidon** [comment]
@pwalsh what is the difference between _Replace file_ button in the left of file field and cross button in the right of it?

**Comment by pwalsh** [comment]
cross button remove field (and file)

replace leaves field, but adds a different file to field (ie: user chooses a new file from local machine)

**Comment by gvidon** [comment]
- [x] upload progress — percents in the right of submit button

**Comment by gvidon** [comment]
Can't show progress as most time spent on CSV parsing and there is no API for requesting progress state.

Instead of progress percents show file processing stages — _Uploading_, which is instantly replaced with _Parsing_ and finally _Validating_.

**Comment by pwalsh** [comment]
@gvidon just noticed you added this. Please don't spend time on new tasks like this, until the [existing task list is finished](https://github.com/openspending/os-import/issues/11#issuecomment-134936048) :).

**Comment by gvidon** [comment]
@pwalsh probably I did uploading different from what we need. What I did is
- upload-parse-validate file in background
- and when done append to the list.

Do we need
- append file to the list
- show its spinner (not global one) while it is in progress
- upload-parse-validate file in background
- turn off loading state?

**Comment by gvidon** [comment]
- [x] only one file for upload
